### ISSUE TITLE
[Suggestion]: Make raft types datapack tag dependent

### ISSUE THREAD

**Issue by KittenRaee** [Mrbysco/JustARaftMod#10]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Instead of having limited hard coded raft types, it would be much more beneficial if rafts took tag (\#minecraft:logs) and generated raft types dynamically based on log type supplied for automatic and painless mod support for every mod.

**Comment by Mrbysco** [comment]
Not really viable to do
