### ISSUE TITLE
 Forge modname problem

### ISSUE THREAD

**Issue by Mari023** [Mrbysco/JustARaftMod#6]
This mod doesn't work with Just Another Ruby Mod, becuase it uses the same name (jarm)

**Comment by NicosaurusRex99** [comment]
https://github.com/NicosaurusRex99/JARMGit/issues/6 , please change your MODID to something like raftmod

**Comment by Mrbysco** [comment]
@NicosaurusRex99 The thing is. That'd be a breaking change and could cause issues with SevTech

**Comment by NicosaurusRex99** [comment]
I have the same problem, my mod is in some other packs too, and it would mean changing over 350 json files. I think we will just have to let this issue be at the moment.

**Comment by NicosaurusRex99** [comment]
in 1.13.2 i will change my modid so if you update we should be compatable
