### ISSUE TITLE
Bamboo Rafts

### ISSUE THREAD

**Issue by Darkfiend009** [Mrbysco/JustARaftMod#9]
## SUGGESTIONS
- [x] I would like to propose new content.
- [ ] I would like to propose changes.
- [ ] I would like to propose another thing.

<!-- SUGGESTIONS INFORMATION - Please explain what you want changed/added and why.
## SUGGESTIONS INFORMATION 
I would love to see rafts be craftable with bamboo now that Minecraft has added it as a vanilla resource. It would be very - aesthetically pleasing and offer a little more variation!

**Comment by Darkfiend009** [comment]
I couldn't get the reason for my suggestion to appear in the template for some reason:

I would love to see rafts be craftable with bamboo now that Minecraft has added it as a vanilla resource. It would be very aesthetically pleasing and offer a little more variation!

**Comment by Mrbysco** [comment]
Will see what I can do :D
